type: object
required:
  - data
properties:
  data:
    description: The Task completion payload.
    title: Complete Task Data Builder
    oneOf:
      - type: array
        items: {}
      - type: object
