type: object
properties:
  id:
    $ref: definitions.yaml#/task_id
  workflow_run_id:
    type: string
    format: uuid
    description: The workflow run id the task belongs to.
  task_def_id:
    $ref: definitions.yaml#/task_def_id
  task_def_version:
    type: string
    nullable: true
    description: The task definition version.
  input:
    type: object
    description: Input object with the fields used by the Task to execute.
  output:
    type: object
    nullable: true
    description: Output object with the fields produced by the Task execution.
  created_at:
    type: string
    format: date-time
    description: The date and time when the Task was created.
  updated_at:
    type: string
    format: date-time
    description: The date and time when the Task was last updated.
