gitRepoId: onfido-ruby
gemVersion: ${CLIENT_LIBRARY_VERSION}
gemName: onfido
gemHomepage: https://github.com/onfido/onfido-ruby
gemLicense: MIT
gemSummary: The official Ruby library for integrating with the Onfido API.
gemDescription: Ruby Library for the Onfido API
httpUserAgent: onfido-ruby/${CLIENT_LIBRARY_VERSION}
files:
  LICENSE.mustache:
    destinationFilename: LICENSE
  .markdownlint.mustache:
    destinationFilename: .markdownlint.json
  webhook_event_verifier.mustache:
    destinationFilename: lib/onfido/webhook_event_verifier.rb
