gitRepoId: onfido-python
distributionPackageName: onfido-python
packageName: onfido # i.e. import package name
packageVersion: ${CLIENT_LIBRARY_VERSION}
useOneOfDiscriminatorLookup: true
httpUserAgent: onfido-python/${CLIENT_LIBRARY_VERSION}
files:
  LICENSE.mustache:
    destinationFilename: LICENSE
  .markdownlint.mustache:
    destinationFilename: .markdownlint.json
  webhook_event_verifier.py:
    folder: onfido
